steps:
    - commands:
          - "swift package clean"
          - "swift build"
          - "swift test"
          - "cd Demos; xcodebuild -scheme 'SwiftFormatsDemo' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0' build"
          #- "swiftlint lint --quiet"
